### PR TITLE
Make loading default model easier, allow specifying encoding, and optionally preserve whitespace when segmenting

### PR DESCRIPTION
**Pull request by ConstantineLignos**
This addresses a number of issues that we ran into when integrating DetectorMorse into our pipeline at ISI:

1. `detector.slurp` uses the default encoding and doesn't allow it to be specified. This PR sets a default of `utf-8` and allows the user to specify a different value.
2. The model isn't installed alongside the package, making it trickier to use. This PR adds the WSJ model as a resource and enables loading it using `detector.default_model()`.
3. Segmentation is destructive as it will `rstrip` each sentence before returning it. This poses a problem for offset-preserving systems. This PR adds an argument `strip=True` to `Detector.segments`; when it is set to `False` whitespace is not stripped.

I've added tests under `/tests` which exercise the default model and the whitespace stripping. (I tried to tie these into `setup.py test`, but I couldn't sort out an issue where the test collector seemed to call `__main__.py`, which crashes without arguments.)

Along the way, just to prevent annoyances, I ended up stripping trailing whitespace and removing unused imports.

If https://github.com/cslu-nlp/nlup/pull/2 is merged, this package should be pip-installable at this point.

### CODE REVIEW

**Comment by kylebgorman** [comment]
This looks good. A few suggestions before we merge:

* nlup version on pip is now 0.7: perhaps you want to upgrade this as well
* we should support the non-destructive stripping at the script level, too, don't you think? There needs to be a flag for that.

**Comment by ConstantineLignos** [comment]
PR has been updated to:
1. Reflect new nlup version
2. Add the `--preserve-whitespace` flag
3. Correct the issue I mentioned in chat that sentences that end in newline were not being segmented. I added tests to ensure that sentence-medial newlines are still being passed through.

There could be more done to spruce up the command line usage. The thing I think most worth doing is to have it use the default model automatically. Right now if this was pip-installed, you'd have to find the model in the package location and pass it to `-r` to get the default model loaded.

Two ideas here:
1. Allow `-r` with no argument to be the default model
2. If neither `-t` nor `-r` are specified,  default to `-r` with the default model.

Do either of those sound good?

**Comment by kylebgorman** [comment]
I don't love either but I prefer #1.

**Comment by ConstantineLignos** [comment]
This now implements (1) above, so you can do the following to use the default model: `python -m detectormorse -r -s test.txt`.

**Comment by ConstantineLignos** [comment]
This merits a README update, I'll do that now.

**Comment by ConstantineLignos** [comment]
README updated.

**Pull request merged**
